### ISSUE TITLE
A bit more overlap in the milling path is needed

### ISSUE THREAD

**Issue by koppi** [pcb2gcode/pcb2gcode#14]
Is it possible to add a bit of "overlap" between a milling path's start and end point? There are some bridges in my first try to mill a PCB, see:
![img_20150610_195115](https://cloud.githubusercontent.com/assets/9458631/8091091/f99a0fdc-0fb1-11e5-8c9a-4fa480ed4545.jpg)

https://github.com/koppi/arduino-shield

**Comment by Corna** [comment]
I've never had this problem, but other users in the previous years have reported the same issue. I'll investigate

**Comment by koppi** [comment]
I'm running this on LinuxCNC, is the "G64 P0.05080 ( set maximum deviation from commanded toolpath )" relevant here?

**Comment by Corna** [comment]
From your Makefile I see that you're using metric units, therefore that G64 code allows a maximum deviation of 0.05 mm, not enough to create those errors

**Comment by koppi** [comment]
While pcb2gcode currently outputs "mathematical correct" milling paths, it would be really helpful to have a bit of overlap between the current end and start points. I think, every machine has some backslash and tolerances, if you could add this as a feature I will test it.

**Comment by Corna** [comment]
Can you please mill the same circuit in the same conditions with the optimisation turned off? I think that it's an optimisation bug

**Comment by koppi** [comment]
Here are the two versions with and without optimise:
* [arduino-shield-no-opt_back.ngc](http://paste.ubuntu.com/11701615/)
* [arduino-shield-opt_back.ngc](http://paste.ubuntu.com/11701617/)
Whenn I CNC arduino-shield-no-opt_back.ngc, I get the correct results.

**Comment by Corna** [comment]
It was a simplifypath bug
I've finally added Boost.Geometry and I've replaced the local geometric algorithms (pointDistance and simplifypath) with the Boost implementation (boost::geometry::distance and boost::geometry::simplify, that is Douglas-Peucker)
The milling files are now slightly larger, but they are much more precise (for example, circles with simplifypath were horrible) and this bug should now be fixed
Can you please pull the code from the new [boost_geometry](https://github.com/pcb2gcode/pcb2gcode/tree/boost_geometry) branch and test if the problem is still present with the optimisation turned on?

**Comment by koppi** [comment]
Just tested it withe the boost_geometry branch, results look much better now.

**Comment by Corna** [comment]
Perfect!
Thanks for your help
