### ISSUE TITLE
Windows Build?

### ISSUE THREAD

**Issue by g4eml** [pcb2gcode/pcb2gcode#488]
Has anyone managed to build Windows binaries for the latest versions of pcb2gcode and pcb2gcodeGUI? 

I have tried for several hours today to build my own by following the instructions here. However I had no success, I could not build gerbv and so could get no further.  The gerbv make command is failing with several 'Multiple definition' errors from the linker and I have not been able to resolve them.

**Comment by eyal0** [comment]
This is related to #453

**Comment by bjanders** [comment]
Related to this, README.md should remove the text "Windows prebuilt binaries (with all the required DLLs) are available in the release page." since there apparently aren't any prebuild binaries. I didn't spend a lot of time noticing this, so not a big issue, but kind of frustrating looking all over the place thinking you are doing something wrong.

**Comment by eyal0** [comment]
This is fixed by b88a2fbd and 011336db and 6d15f726
