### ISSUE TITLE
Most paths get milled twice using voronoi mode

### ISSUE THREAD

**Issue by zagl** [pcb2gcode/pcb2gcode#60]
With the current git version (2017-01-12) when using voronoi mode every every copper piece is milled completely. Thus, all borders between touching surfaces get milled twice.

For example I used this Gerber layout:
![gerber](https://cloud.githubusercontent.com/assets/5967081/21953958/00e15322-da45-11e6-9a20-f4b4de349e63.png)

This is traced as follows in voronoi mode:
![traced](https://cloud.githubusercontent.com/assets/5967081/21953970/3a8e9c42-da45-11e6-8a83-7749f09f218e.png)

In the following picture I marked every single mill path. It is obvious that nearly every path is milled twice.
![mill_paths](https://cloud.githubusercontent.com/assets/5967081/21953961/0be86b5c-da45-11e6-9658-c0a18b0c972a.png)

One advantage of using voronoi could be that it is possible to nearly half the processing time. But in this case the processing time is nearly the same or even longer.

Is it possible to detect already milled paths and skip these?

**Comment by eyal0** [comment]
@zagl I'm working on this.  If I get it working, would you be interested in testing it?

**Comment by eyal0** [comment]
Here's a pretty good attempt:

![2017-12-17-161419_1744x460_scrot](https://user-images.githubusercontent.com/109809/34080395-a797aa22-e345-11e7-9bab-590c2d7392ca.png)

We can see in the image that the two paths for the input are visually identical.  However, the left path is about half the length because it doesn't do each trace twice, only once.

**Comment by eyal0** [comment]
This issue is solved with eulerian-paths mode in vectorial, which is on by default.
