### ISSUE TITLE
Weird extraneous cut

### ISSUE THREAD

**Issue by DagAgren** [pcb2gcode/pcb2gcode#603]
## Description of bug:

I have an otherwise perfectly working project set up that generates g-code for a single-sided board using Voronoi mode. The SVG output shows the exactly correct board for the given settings and input files, but the generated gcode includes one short cut that is not in the SVG and is not correct. It looks like the spindle needs to retract and move to a nearby point, but instead it just mills straight through.

Luckily, for this board it is cutting through bits that are mostly NC, but it does cut away a small part of an actually used solder pad, and of course it is a visual blemish.

## pcb2gcode version (run pcb2gcode --version to see this):

2.4.0
Git commit: 
Boost: 107500
Gerbv: 2.7.0
Geos: Not installed

[Project.zip](https://github.com/pcb2gcode/pcb2gcode/files/7803979/Project.zip)

<img width="715" alt="Screenshot 2022-01-03 at 22 49 56" src="https://user-images.githubusercontent.com/11536828/147979520-c57beda9-f18c-4953-9ad2-9daf97b43f74.png">
<img width="801" alt="Screenshot 2022-01-03 at 22 50 04" src="https://user-images.githubusercontent.com/11536828/147979522-20fee17c-8514-416a-895b-16ce43dfccb2.png">

**Comment by eyal0** [comment]
First I'll explain what's going on and then offer a couple solutions.

This is a optimization feature.  pcb2gcode computed that it would be faster to cut across then to lift the tool, move, and set it back down.  If you examine the file `processed_back_final.svg`, you can see the path that the tool it taking:

![image](https://user-images.githubusercontent.com/109809/148146049-f2061755-272e-412e-976a-6179c9ad2b62.png)

The black line is correctly avoiding entering any traces.

The reason that you're seeing it actually cut in is because you didn't tell pcb2gcode the width of the milling tool, so it assumed 0.  Here is what it looks like if I run `pcb2gcode --mill-diameters=0.5mm`:

![image](https://user-images.githubusercontent.com/109809/148150221-d12dd60c-871e-4e6c-8756-a9701e10b9b2.png)

See that light-green shading?  That's the width of the mill.  You'll also get some new warnings:

```
Warning: pcb2gcode hasn't been able to fulfill all clearance requirements.  Check the contentions output and consider using a smaller milling bit.
```

That's because 0.5mm was too big to mill some thermal reliefs:

![image](https://user-images.githubusercontent.com/109809/148150415-654833d6-30f7-452d-a8d0-b647f337ce2a.png)

The one on the right was milled, the one on the left wasn't.  If you don't care then no big deal!

That big vertical cut is still there because it was computed to be faster than lifting and lowering again.

Like I said before, the reason that the milling bit cut across diagonally is because it was faster than lifting and lowering.  You can tell pcb2gcode to not do any of these shortcuts by setting the `--path-finding-limit=0`.  Like this:

![image](https://user-images.githubusercontent.com/109809/148150683-9b37ad3c-f393-4684-b982-848d2b1f9bec.png)

So my recommendation is that you measure your milling bit's width and set `--mill-diameters`.  And then, if you still don't like the result, then consider messing with the path-finding-limit.

The wiki discusses all of these, too.  https://github.com/pcb2gcode/pcb2gcode/wiki

I hope that this solves your problem!  Re-open this issue if you need more help with it.
