### ISSUE TITLE
Align trace milling operation with soldermask operation

### ISSUE THREAD

**Issue by dzervas** [pcb2gcode/pcb2gcode#605]
## Description of bug:
I'm trying to add soldermask to my PCBs in order to have super thin trace clearance that won't be solder bridged. I ended up running pcb2gcode 2 times: one to produce back side of the traces, drills, outline and one to produce the back soldermask milling.
To mill the soldermask you have to mill the inside of the pad. The problem is that the soldermask gcode is not aligned with the trace gcode.

## What did you try (include command-line arguments):
1. Run pcb2gcode to generate back (actual trace milling), drill & outline
2. Run pcb2gcode to generate back soldermask but re-generate outline so that the absolute min/max dimensions are the same and the gcodes aligned
3. Mill back
4. Apply soldermask
5. Mill soldermask back
6. Drill
7. Outline

## What happened:
The pads removed on the soldermask are about a millimeter off in both X & Y (can't measure the exact difference)

## What did you expect to happen:
Both back and soldermask-back to be aligned

## pcb2gcode version (run pcb2gcode --version to see this):
```
2.4.0
Git commit: 1f54bea
Boost: 107500
Gerbv: 2.7.0
Geos: Not installe
```

Please attach your input files and relevant output files and images.  **Don't forget to include your millproject file and gerbers!**  You might need to zip them.  If you don't provide a millproject file, make sure that you copy-paste the command-line that you used.

To generate the soldermask, I used the same millproject but I also added these flags: `--isolation-width=1000mm --invert-gerbers=1 --zwork=-0.001`
[gcode.zip](https://github.com/pcb2gcode/pcb2gcode/files/7836320/gcode.zip)
[gerbers.zip](https://github.com/pcb2gcode/pcb2gcode/files/7836321/gerbers.zip)
[millproject](https://github.com/pcb2gcode/pcb2gcode/files/7836325/millproject.txt)

**Comment by eyal0** [comment]
When I ran pcb2gcode, it didn't work because there are no files specified in your millproject.  Could you please send the *exact* command that you ran?

Without knowing the command that you ran, I'm not totally sure, but I suspect that the problem might be that you ran the program that first time with outline and the second time without.

With `zero-start=true`, which is the default and also what you have in your millproject, `pcb2gcode` will move your project so that it fits in the first quadrant.  It measures how big your project is and slides everything over so that it will all sit just above the x axis and just to the right of the y axis.  First quadrant.

If you provide a different set of input files then the size of the project can change.  For example, you might run it once with the outline and once without.  So the width of the outline will not be accounted for and the project will be in a different place.

If you set `zero-start=false` then pcb2gcode will not slide your project over so that it sits in the first quadrant.  It'll just use whatever coordinates that you originally had in your project.  You can set the x and y offset of your CNC machine so that the milling will not fall off the edges of the CNC platform and it'll all work out.  If you don't, then the milling might go off the edge of the machine.  This option is sometimes called the "work coordinate system".

So, assuming that I'm right about your problem, you have two options:

1. Make sure that the input files are the same in both cases.
2. Use `zero-start=false`

Read more: https://github.com/pcb2gcode/pcb2gcode/wiki/Options:-Alignment-for-two-sided-PCB-and-offsets#zero-start

If this doesn't help you, please re-open this issue and provide the actual command-line that you ran.
