### ISSUE TITLE
Path cut line to pcb board

### ISSUE THREAD

**Issue by cacheflood** [pcb2gcode/pcb2gcode#627]
Line segment cut through existing shapes and cut paths.

Dunno should that move be rapid or is the solver somehow broken?
![Screenshot from 2022-08-26 01-08-27](https://user-images.githubusercontent.com/5121781/186777639-ce81eec3-6c99-4279-853e-e8968599d335.png)

version:
2.4.0
Git commit: latest-22-ge51ef9e5
Boost: 107600
Gerbv: 2.9.2
Geos: Not installed

Files to reproduce(?):

[tilulilu.zip](https://github.com/pcb2gcode/pcb2gcode/files/9428513/tilulilu.zip)

**Comment by eyal0** [comment]
The problem seems to be because you don't have geos installed.  The boost polygon library, though I really like using it, has some flaws.  :-(  And it's not so fast, either.  One of the flaws is that is causes errors in the output.  Usually they are minor but in your case it's a big one!

Here's the version without geos:

```
2.4.0
Git commit: v2.4.0-66-gd9f5a6f6
Boost: 106600
Gerbv: 2.7.0
Geos: Not installed
```

![image](https://user-images.githubusercontent.com/109809/187258005-68e08a30-7f87-4438-9537-bdb42f68bba0.png)

To install geos++ and recompile, I issued these commands:

```bash
sudo apt-get install libgeos++-dev
autoreconf -fvi && ./configure BOOST_ROOT${HOME}/private/boost/boost1.66 pcb2gcode_CPPFLAGS_EXTRA="-Wall -Werror" --disable-silent-rules --enable-static --disable-shared && make clean && make -j 20
```

Now the version is:

```
2.4.0
Git commit: v2.4.0-66-gd9f5a6f6
Boost: 106600
Gerbv: 2.7.0
Geos: 3.9.0
```

And now my output is:

![image](https://user-images.githubusercontent.com/109809/187259317-81e9d02e-6b75-4a2c-a293-81ffd514c86d.png)

If this doesn't solve your problem, please re-open the issue.  Thanks!

**Comment by cacheflood** [comment]
Thank you for the information, you guys are doing a great job  ! :)

-Jani

ma 29. elok. 2022 klo 20.21 Eyal ***@***.***) kirjoitti:
